name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD  🚀
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Pujar-a-produccio"
  Pujar-amb-vue-a-produccio:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Obtenint el codi del respositori
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      # Sets up node and npm dependencies
      - name: Instalant node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0


      # Runs a set of commands using the runners shell
      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          cd ./PelisVue/
          npm install
          npm run build --if-present
          echo "Action desplegant a produccio" > ./dist/last_deploy.txt
          date >> ./dist/last_deploy.txt
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a21marbenalc/web/marben.daw.inspedralbes.cat/public_html/web2/
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
